version: 2.1

executors:
    gcc9:
        docker:
            - image: conanio/gcc9
              environment:
                  CXX: g++-9
                  CC: gcc-9
                  CMAKE_BUILD_FLAGS:
                  CTEST_FLAGS: --output-on-failure --verbose

commands:
    build_gtest:
        steps:
            - run: cd third_party
            - run: git submodule init
            - run: git submodule update

    install_cmake:
        steps:
            - run: sudo apt-get update -qq
            - run: sudo apt-get install -y cmake

    cmake_build_debug:
        steps:
            - run: cmake -Bbuild $CMAKE_FLAGS
            - run: cmake --build build --config Debug

    cmake_unit_test:
        steps:
            - run: |
                cd build
                ./unit_test --verbose --gtest_output=json

    cmake_test:
        steps:
            - checkout
            - build_gtest
            - install_cmake
            - cmake_build_debug
            - cmake_unit_test

jobs:
    build-and-test-gcc9:
        description: Build repo
        executor: gcc9
        environment: { CMAKE_FLAGS: -DCMAKE_BUILD_TYPE=Debug }
        steps: [ cmake_test ]


workflows:
    version: 2.1
    build-and-test:
        jobs:
            - build-and-test-gcc9

