version: 2.1

executors:
    gcc9:
        docker:
            - image: conanio/gcc9
              environment:
                  CXX: g++-9
                  CC: gcc-9
                  CMAKE_BUILD_FLAGS:
                  CTEST_FLAGS: --output-on-failure --verbose

commands:
    build_gtest:
        description: Build GTest from submodule
        steps:
            - run: |
                cd third_party
                git submodule init
                git submodule update

    install_cmake:
        description: Install cmake
        steps:
            - run: |
                sudo apt-get update -qq
                sudo apt-get install -y cmake

    cmake_build:
        description: Create build directory
        steps:
            - run: cmake -Bbuild $CMAKE_FLAGS

    cmake_unit_test:
        description: Build and run unit_test
        steps:
            - cmake_build
            - run: |
                cd build
                make unit_test
                ctest $CTEST_FLAGS

    cmake_test:
        description: Workflow to run all test
        steps:
            - checkout
            - build_gtest
            - install_cmake
            - cmake_unit_test

jobs:
    build-and-test-gcc9:
        description: Build repo
        executor: gcc9
        environment: { CMAKE_FLAGS: -DCMAKE_BUILD_TYPE=Debug, CTEST_FLAGS: --output-on-failure --verbose }
        steps: [ cmake_test ]


workflows:
    version: 2.1
    build-and-test:
        jobs:
            - build-and-test-gcc9

