name: Codacy Analysis CLI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install clang-tidy
        run: sudo apt install clang-tidy

      - name: Run clang-tidy
        continue-on-error: true
        run: clang-tidy $(find src -name "*.cc" -o -name "*.hh") -extra-arg=-std=c++17 -- -Isrc/engine > clang-tidy-output

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
          max-allowed-issues: 2147483647
          clang-tidy-output: "clang-tidy-output"
          run-docker-tools: "false"
