name: Codacy Analysis CLI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
          max-allowed-issues: 2147483647
          clang-tidy-output: "clang-tidy-output"
          run-docker-tools: "false"
